version: "3.8"
services:
  dynamodb-local:
    command: "-jar /home/dynamodblocal/DynamoDBLocal.jar -sharedDb
-dbPath /data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "9000:8000"
    volumes:
      - "dynamodb:/data"
    user: root
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "9001:9001"
    environment:
      - PORT=9001
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000

  minio:
    image: minio/minio
    command: server /data --console-address ":9002"
    ports:
      - "9002:9000" # S3
      - "9003:9002" # S3 console
    volumes:
      - "minio:/data"
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/local;
      /usr/bin/mc policy set public myminio/local;
      exit 0;
      "
volumes:
  dynamodb:
  minio:
