services:
  chain:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command:
      [
        "--chainId",
        "31337",
        "--mnemonic",
        "analyst decade album recall stem run cage ozone human pepper once insect",
        "--accounts",
        "20",
        "--noVMErrorsOnRPCResponse",
      ]

  deploy_contract:
    image: sismo/sismo-protocol:v1.0.3-alpha
    environment:
      - LOCAL_HOSTNAME=chain
    command: ["./scripts/wait-for-local-chain.sh", "yarn", "deploy:local"]
    restart: on-failure:3

  relayer:
    image: sismo/sismo-simple-relayer:v1.0.4-alpha
    environment:
      - NODE_ENV=local
      - LOCAL_HOSTNAME=chain
    ports:
      - "8081:8080"

  frontend:
    image: sismo/sismo-app:v1.0.12-alpha
    ports:
      - "3000:80"
