
import { Tags, ValueType, GroupWithData } from "topics/group";
import {
  GenerationContext,
  GenerationFrequency,
  GroupGenerator,
} from "topics/group-generator";

const generator: GroupGenerator = {
  
  generationFrequency: GenerationFrequency.Daily,
  
  generate: async (context: GenerationContext): Promise<GroupWithData[]> => {
  
    const builders = {
      "telegram:change_000":"1",
      "telegram:developerSec":"1",
      "telegram:AnotherDaveOk":"1",
      "telegram:luksgrin":"1",
      "telegram:frayeX":"1",
      "telegram:casocasocaso":"1",
      "telegram:wslyvh":"1",
      "twitter:bianc8_eth":"1",
      "telegram:kprasch":"1",
      "twitter:arjanjohan":"1",
      "telegram:theref_eth":"1",
      "telegram:owencampbell":"1",
      "telegram:theolefur":"1",
      "telegram:AidEn_PeArce0":"1",
      "telegram:L0GYKAL":"1",
      "telegram:alberto_centonze":"1",
      "twitter:lFinBob":"1",
      "telegram:Patrickous":"1",
      "telegram:kvncnls":"1",
      "twitter:CooperJamshed":"1",
      "telegram:gaylordwarner":"1",
      "twitter:grmkris":"1",
      // "twitter:GuillermoTala":"1", // suspended account
      "twitter:ChefShokumotsu":"1",
      "telegram:lolchto":"1",
      "twitter:0xFrytos":"1",
      "twitter:andredbsc":"1",
      "twitter:Ushana34655283":"1",
      "telegram:rraigal":"1",
      "telegram:remicase":"1",
      "twitter:ammarif_":"1",
      "twitter:NelsonRodMar":"1",
      "twitter:guelowrd_":"1",
      "twitter:seanwbren":"1",
      "telegram:quiker":"1",
      "telegram:kaijuneer":"1",
      "twitter:vovunku":"1",
      "telegram:Jrastit":"1",
      "twitter:Huxwell_":"1",
      "telegram:taijusanagi":"1",
      "telegram:catmcgee":"1",
      "twitter:HxSimo":"1",
      "twitter:LGelinet":"1",
      "twitter:dydymoon1":"1",
      "twitter:nezzRX":"1",
      "telegram:deepcryptodive":"1",
      "telegram:zpedro":"1",
      "twitter:danimbrogno":"1",
      "twitter:devnull03":"1",
      "twitter:wired_hikari":"1",
      "github:monochrome9":"1",
      "twitter:Bayka":"1",
      "twitter:0xbyyou":"1",
      "telegram:ara11313":"1",
      "telegram:juliomcruz":"1",
      "github:Laser420":"1",
      "twitter:chimeraDefi":"1",
      "twitter:FishFishDeFi":"1",
      "twitter:liam_nft_96":"1",
      "twitter:hourglasshoro":"1",
      "twitter:takuya950413":"1",
      "twitter:0xTiff":"1",
      "twitter:vparv3":"1",
      "twitter:yogeshdarji99":"1",
      "github:kMongru":"1",
      "github:WiserRiser":"1",
      "twitter:rapchan":"1",
      "github:alexeipancratov":"1",
      "twitter:Eroica32":"1",
      "twitter:matthew_glezos":"1",
      "twitter:shubh_aga":"1",
      "twitter:WEBthe3rd":"1",
      "telegram:bonjour17":"1",
      "twitter:acolexyz":"1",
      "telegram:LarryLeftwood":"1",
      "twitter:DicksonWuML":"1",
    };

    return [
      {
        name: "sismo-hackathons-participants",
        timestamp: context.timestamp,
        description: "Hackathons participants who built on Sismo",
        specs: "This group consist of all the hackers that built on Sismo during hackathons",
        data: builders,
        valueType: ValueType.Score,
        tags: [Tags.Builders, Tags.Maintained],
      },
    ];
  },
};

export default generator;
