import { Tags, ValueType, GroupWithData, AccountSource } from "topics/group";
import { GenerationContext, GenerationFrequency, GroupGenerator } from "topics/group-generator";

// Generated from factory.sismo.io

const generator: GroupGenerator = {
  generationFrequency: GenerationFrequency.Once,

  generate: async (context: GenerationContext): Promise<GroupWithData[]> => {
    return [
      {
        name: "jiraya-og-badge",
        timestamp: context.timestamp,
        description: "Be part of the best contributors on the 'JiRaYa-OG' Twitter account (Likes, Retweets, Comments, Giveaways participation, account promotion, etc...)",
        specs: "Follow 'JiRaYa-OG' on Twitter Like, Retweet, comment on posts and threads, Recommend the 'JiRaYa-OG' account on social networks, Participate in Giveaways, be one of the most active members of the community",
        data: {
          "twitter:DareinHisoka": "1",
          "twitter:parradvd": "1",
          "twitter:Bustaaal1": "1",
          "twitter:alexandresauv13": "1",
          "twitter:NaturoCrypto": "1",
          "twitter:FastKsh": "1",
          "twitter:SpongeBobby91": "1",
          "twitter:mjul23": "1",
          //"twitter:Lucas_Crypto_FR": "1",
          "twitter:Crypt0culus": "1",
          "twitter:crypto_omg": "1",
          "twitter:SteufDab": "1",
          "twitter:Kernoff13": "1",
          "twitter:RoroYonko": "1",
          "twitter:Epsylone_eth": "1",
          "twitter:Funky80310": "1",
          "twitter:KidPaddle591": "1",
          "twitter:Fred02049414": "1",
          "twitter:0ctavescalp": "1",
          "twitter:Lovemeandsaveme": "1",
          "twitter:lemxnvde9": "1",
          "twitter:antoinemarchain": "1",
          "twitter:lionel_tlse": "1",
          "twitter:ZerGam_": "1",
          "twitter:THE_FAHRENHEIT": "1",
          "twitter:julienando49": "1",
          "twitter:mikemik76032417": "1",
          "twitter:N0rma2n_G": "1",
          "twitter:JMout25": "1",
          "twitter:M4x1m9": "1",
          "twitter:VDAaaaaaaa": "1",
          "twitter:Bad_Ass_78": "1",
          "twitter:Finally_JC": "1",
          "twitter:mrreckt1": "1",
          "twitter:BananeBleue5": "1",
          "twitter:AirdropJerem1": "1",
          "twitter:Ravnicadu44": "1",
          "twitter:0xAlbo": "1",
          "twitter:Simk933": "1",
          "twitter:salameche172": "1",
          "twitter:Braxy09": "1",
          "twitter:erdBlackHat": "1",
          "twitter:ravalapache": "1",
          "twitter:maXoulapince": "1",
          "twitter:pouppypupets": "1",
          "twitter:darth_nihil7s": "1",
          "twitter:VL_Morghulis": "1",
          "twitter:phildubassin33": "1",
          "twitter:Cedric93203219": "1",
          "twitter:Pompavelaooo": "1",
          "twitter:SgardSebastien": "1",
          "twitter:Kvn2743": "1",
          "twitter:florentgd1": "1",
          "twitter:taig006": "1",
          "twitter:Didoouzz": "1",
          "twitter:1sociaLx": "1",
          "twitter:CryptoLFDM": "1",
          "twitter:Jordan_Dslv": "1",
          "twitter:jonatha31660624": "1",
          "twitter:Flowg00": "1",
          "twitter:BungaKiwa": "1",
          "twitter:JiRaYa_OG": "1",
          "twitter:Ghrond_HS": "1",
          "twitter:Riko45Ls": "1",
        },
        accountSources: [AccountSource.ETHEREUM],
        valueType: ValueType.Score,
        tags: [Tags.Factory],
      },
    ];
  },
};

export default generator;
