import {
  hydraS1AccountboundAttester,
  hydraS1AccountboundBadges,
} from "@badges-metadata/main/hydra-s1-accountbound";
import { Network } from "topics/attester";
import { Flow } from "topics/flow";

export const mainFactoryFlows: Flow[] = [
  {
    path: "helper",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2017027],
    title: "",
    logoUrl: null,
    subtitle: "Mint Helper",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zen",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2018840],
    title: "",
    logoUrl: null,
    subtitle: "Mint zen",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "gen-0-dagorians",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2027048],
    title: "",
    logoUrl: null,
    subtitle: "Mint Gen[0] dAgorians",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sismo-meme",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2020053],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sismo meme",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "kukushkinace",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2030012],
    title: "",
    logoUrl: null,
    subtitle: "Mint kukushkinace",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "roxxypoxxy",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2041821],
    title: "",
    logoUrl: null,
    subtitle: "Mint RoxxyPoxxy",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zklend-poap-contributor",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2042020],
    title: "",
    logoUrl: null,
    subtitle: "Mint zkLend POAP contributor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "baby2father-eth",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2052047],
    title: "",
    logoUrl: null,
    subtitle: "Mint baby2father.eth",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rahulkr-lens-followers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2055365],
    title: "",
    logoUrl: null,
    subtitle: "Mint RAHULKR LENS FOLLOWERS",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "akaps-frens",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2061601],
    title: "",
    logoUrl: null,
    subtitle: "Mint AKAPS FRENS",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "the-sandbox-contributor",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2062663],
    title: "",
    logoUrl: null,
    subtitle: "Mint The Sandbox Contributor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lens-meme-collector-mirror",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2064170],
    title: "",
    logoUrl: null,
    subtitle: "Mint LENS meme collector,mirror",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "weed-lover-become-follower",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2070706],
    title: "",
    logoUrl: null,
    subtitle: "Mint Weed Lover Become Follower",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "wojak-lens",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2087460],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wojak Lens ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tokenomics-dao-consultant",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2092300],
    title: "",
    logoUrl: null,
    subtitle: "Mint Consultant",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mannyradu",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2100600],
    title: "",
    logoUrl: null,
    subtitle: "Mint MannyRadu",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "my-1",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2106109],
    title: "",
    logoUrl: null,
    subtitle: "Mint My 1",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "coin-center-donators",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Polygon, Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2106633],
    title: "",
    logoUrl: null,
    subtitle: "Mint Coin Center Donator",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "umanuma-lens-followers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2129060],
    title: "",
    logoUrl: null,
    subtitle: "Mint umanuma.lens followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "viktor",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2137451],
    title: "",
    logoUrl: null,
    subtitle: "Mint Viktor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mice-derp-early",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2138501],
    title: "",
    logoUrl: null,
    subtitle: "Mint MICE dERP Early",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zkpay-finance-azf7",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2139448],
    title: "",
    logoUrl: null,
    subtitle: "Mint ZKPAY.finance-AZF7",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "first-rug-on-lens",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2140799],
    title: "",
    logoUrl: null,
    subtitle: "Mint First Rug on Lens Protocol",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "vegan",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2143017],
    title: "",
    logoUrl: null,
    subtitle: "Mint vegan",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mahadev",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2144122],
    title: "",
    logoUrl: null,
    subtitle: "Mint Mahadev",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zl019",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2145326],
    title: "",
    logoUrl: null,
    subtitle: "Mint ZL019",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "web3-developer",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2153491],
    title: "",
    logoUrl: null,
    subtitle: "Mint Web3 Developer",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "monsters",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2153882],
    title: "",
    logoUrl: null,
    subtitle: "Mint Monsterwear",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "digi",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2155948],
    title: "",
    logoUrl: null,
    subtitle: "Mint Digi",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "commitdao",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2163624],
    title: "",
    logoUrl: null,
    subtitle: "Mint CommitDAO",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "vorontein-folowers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2165888],
    title: "",
    logoUrl: null,
    subtitle: "Mint Vorontein folowers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lama-pama",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2174030],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lama Pama",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cryptomonkeys",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2184873],
    title: "",
    logoUrl: null,
    subtitle: "Mint CryptoMonkeys ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "madmax-badge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2184978],
    title: "",
    logoUrl: null,
    subtitle: "Mint madmax",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sismo-banana",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2187420],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sismo Banana ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "kingdom",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2192782],
    title: "",
    logoUrl: null,
    subtitle: "Mint kingdom",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cultivatordao-voters",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2194450],
    title: "",
    logoUrl: null,
    subtitle: "Mint Cultivatordao voters",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "martian-wave",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2213141],
    title: "",
    logoUrl: null,
    subtitle: "Mint martianwave",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "relay-badge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2216993],
    title: "",
    logoUrl: null,
    subtitle: "Mint Relay Team",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "onemillion1-lens-followers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2221466],
    title: "",
    logoUrl: null,
    subtitle: "Mint onemillion1.lens followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dropst3r",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2233540],
    title: "",
    logoUrl: null,
    subtitle: "Mint DropSt3r",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "-lrcrypto",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2233728],
    title: "",
    logoUrl: null,
    subtitle: "Mint @lrcrypto",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "with-love-from-bykur",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2234775],
    title: "",
    logoUrl: null,
    subtitle: "Mint With love from bykur",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dorian-gray",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2235119],
    title: "",
    logoUrl: null,
    subtitle: "Mint Dorian Gray",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lyca",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2240012],
    title: "",
    logoUrl: null,
    subtitle: "Mint lyca",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "oldschool",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2240101],
    title: "",
    logoUrl: null,
    subtitle: "Mint Oldschool",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ra",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2245634],
    title: "",
    logoUrl: null,
    subtitle: "Mint Ra",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "neoneo-badge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2248171],
    title: "",
    logoUrl: null,
    subtitle: "Mint NeoNeo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "por",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2250782],
    title: "",
    logoUrl: null,
    subtitle: "Mint por",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lenster-gas-supporter",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2251407],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lenster Gas Supporter",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "chron0n",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2261557],
    title: "",
    logoUrl: null,
    subtitle: "Mint CHRON0n",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zk-hack",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Polygon, Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2267301],
    title: "",
    logoUrl: null,
    subtitle: "Mint ZK Hack",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mybadge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2268502],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wegoham4trey friends",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "aurora",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2274842],
    title: "",
    logoUrl: null,
    subtitle: "Mint shiba",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dorg-members",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Polygon, Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2280940],
    title: "",
    logoUrl: null,
    subtitle: "Mint dOrg",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ukswap",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2283558],
    title: "",
    logoUrl: null,
    subtitle: "Mint ukswap",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "milan",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2286246],
    title: "",
    logoUrl: null,
    subtitle: "Mint milan",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sanyi-s-gift",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2293296],
    title: "",
    logoUrl: null,
    subtitle: "Mint sanyi's gift",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ohjr10",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2298601],
    title: "",
    logoUrl: null,
    subtitle: "Mint ohJR10",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "therealafrorickgroup",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2299239],
    title: "",
    logoUrl: null,
    subtitle: "Mint TheRealAfroRick",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "proof-of-loneliness",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2315671],
    title: "",
    logoUrl: null,
    subtitle: "Mint Proof of Loneliness",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "gem",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2327517],
    title: "",
    logoUrl: null,
    subtitle: "Mint Gem",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dual-pepes",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2329542],
    title: "",
    logoUrl: null,
    subtitle: "Mint Dual Pepes",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "roadtolife2",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2330264],
    title: "",
    logoUrl: null,
    subtitle: "Mint RoadToLife2",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ofac-chads-zk-badge-08-08-2022",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Polygon, Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2336517],
    title: "",
    logoUrl: null,
    subtitle: "Mint OFAC chads",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cyberconnect",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2338189],
    title: "",
    logoUrl: null,
    subtitle: "Mint CyberConnect",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "nftyard-lens-follower",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2340668],
    title: "",
    logoUrl: null,
    subtitle: "Mint Nftyard lens follower",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lens-followers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2345464],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lens Followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "thub-contributor",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2348016],
    title: "",
    logoUrl: null,
    subtitle: "Mint THUB Contributor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "space-inspirers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2355164],
    title: "",
    logoUrl: null,
    subtitle: "Mint Space Inspirers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "soenander33-lens-follows",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2362677],
    title: "",
    logoUrl: null,
    subtitle: "Mint soenander33.lens follows",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "haodi-s-friend",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2364194],
    title: "",
    logoUrl: null,
    subtitle: "Mint Haodi's Friend",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "krishna",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2370898],
    title: "",
    logoUrl: null,
    subtitle: "Mint Krishna",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "flovatar",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2373805],
    title: "",
    logoUrl: null,
    subtitle: "Mint Flovatar",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cryptotelugu-twitter-followers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2375279],
    title: "",
    logoUrl: null,
    subtitle: "Mint CryptoTelugu Twitter Followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "stargate-finance",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2384827],
    title: "",
    logoUrl: null,
    subtitle: "Mint Stargate Finance",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dale1075",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2387087],
    title: "",
    logoUrl: null,
    subtitle: "Mint dale1075",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "supporter-of-100--verified-airdrops",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2387119],
    title: "",
    logoUrl: null,
    subtitle: "Mint Supporter of 100% Verified Airdrops ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mathcastles",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2388060],
    title: "",
    logoUrl: null,
    subtitle: "Mint Mathcastles",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "byrd3885-lens-follows",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2395350],
    title: "",
    logoUrl: null,
    subtitle: "Mint byrd3885.lens follows",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "padultra",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2398819],
    title: "",
    logoUrl: null,
    subtitle: "Mint padultra",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lands",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2399049],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lands",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "katty-rain-followers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2405612],
    title: "",
    logoUrl: null,
    subtitle: "Mint Katty Rain followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "offscript-attendee",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2405819],
    title: "",
    logoUrl: null,
    subtitle: "Mint Offscript attendee",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "roadtolife",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2406685],
    title: "",
    logoUrl: null,
    subtitle: "Mint RoadToLife ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "nastyaleila",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2409288],
    title: "",
    logoUrl: null,
    subtitle: "Mint Nastyaleila",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "kung-fu",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2422521],
    title: "",
    logoUrl: null,
    subtitle: "Mint Kung Fu",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sysmotestbadge1",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2427315],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sysmotestbadge1",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rogue-gang",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2436623],
    title: "",
    logoUrl: null,
    subtitle: "Mint Rogue Gang",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "foxfam-adorator",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2438254],
    title: "",
    logoUrl: null,
    subtitle: "Mint Foxfam Adorator",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cyber",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2440572],
    title: "",
    logoUrl: null,
    subtitle: "Mint Cyber",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dkorshunov",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2461590],
    title: "",
    logoUrl: null,
    subtitle: "Mint DKorshunov",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "empiredao-2023-1-day-desk-pass",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2471201],
    title: "",
    logoUrl: null,
    subtitle: "Mint EmpireDAO 2023 1 Day Desk Pass",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "momoshoten",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2471393],
    title: "",
    logoUrl: null,
    subtitle: "Mint momoshoten",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "alpha-drops",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2471692],
    title: "",
    logoUrl: null,
    subtitle: "Mint Alpha Drops",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "swapper-armyfox",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2481714],
    title: "",
    logoUrl: null,
    subtitle: "Mint Swapper Armyfox",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "byrd2-lens-follow",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2484320],
    title: "",
    logoUrl: null,
    subtitle: "Mint byrd2.lens follow",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rekt-familly-degen",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2484699],
    title: "",
    logoUrl: null,
    subtitle: "Mint REKT Familly degen",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "xnova-lens-follower",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2488109],
    title: "",
    logoUrl: null,
    subtitle: "Mint Xnova lens follower",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zk-hack-iii-sismo-workshop",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2489013],
    title: "",
    logoUrl: null,
    subtitle: "Mint ZK HACK III - Sismo Workshop",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sanye",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2491076],
    title: "",
    logoUrl: null,
    subtitle: "Mint sanye",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "test-badge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2491546],
    title: "",
    logoUrl: null,
    subtitle: "Mint Test Badge",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "wonder",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2493562],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wonder",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "my-09",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2504053],
    title: "",
    logoUrl: null,
    subtitle: "Mint ape",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "my-lens-followers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2511439],
    title: "",
    logoUrl: null,
    subtitle: "Mint My Lens Followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "bodhi",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2512871],
    title: "",
    logoUrl: null,
    subtitle: "Mint Bodhi",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "happy-new-year-2023",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2513097],
    title: "",
    logoUrl: null,
    subtitle: "Mint Happy new year 2023",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tally-ho-github-stargazers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Polygon, Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2513336],
    title: "",
    logoUrl: null,
    subtitle: "Mint Tally Ho Github stargazers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "friends",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2518504],
    title: "",
    logoUrl: null,
    subtitle: "Mint Friends",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ningningfams",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2521946],
    title: "",
    logoUrl: null,
    subtitle: "Mint NingNingFams",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "etherium-eth-bit-5890",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2529316],
    title: "",
    logoUrl: null,
    subtitle: "Mint etherium👍eth.bit#5890",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "jaky",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2532780],
    title: "",
    logoUrl: null,
    subtitle: "Mint jaky",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "kripter",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2535427],
    title: "",
    logoUrl: null,
    subtitle: "Mint kripter",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lenster-supporter",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2536138],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lenster supporter",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rocketlab",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2537705],
    title: "",
    logoUrl: null,
    subtitle: "Mint rocketlab",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tarozzy",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2545069],
    title: "",
    logoUrl: null,
    subtitle: "Mint tarozzy",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "fiona",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2545308],
    title: "",
    logoUrl: null,
    subtitle: "Mint fiona",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mmmemelord",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2548940],
    title: "",
    logoUrl: null,
    subtitle: "Mint mmmemelord",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "wallet-group",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2558435],
    title: "",
    logoUrl: null,
    subtitle: "Mint money dog🐶(OG)",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "gutr0",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2560345],
    title: "",
    logoUrl: null,
    subtitle: "Mint gutr0",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "kongming",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2561850],
    title: "",
    logoUrl: null,
    subtitle: "Mint kongming",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sk",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2569336],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sk",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lenster-early-bloomer",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2569398],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lenster Early Bloomer",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "blockimperiumgames",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2569984],
    title: "",
    logoUrl: null,
    subtitle: "Mint BlockImperiumGames",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "marianmarius",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2571351],
    title: "",
    logoUrl: null,
    subtitle: "Mint MARIANMARIUS",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tokenomics-dao-contributor",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2573021],
    title: "",
    logoUrl: null,
    subtitle: "Mint Tokenomics DAO Contributor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "fortune-badge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2575364],
    title: "",
    logoUrl: null,
    subtitle: "Mint Fortune badge",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zero-knowledge-veteran",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2575988],
    title: "",
    logoUrl: null,
    subtitle: "Mint Zero Knowledge Veteran",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "akamo",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2577616],
    title: "",
    logoUrl: null,
    subtitle: "Mint akamo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "igorsgemsdao",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2579312],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sismo IgorsGemsDao",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mikedoge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2585029],
    title: "",
    logoUrl: null,
    subtitle: "Mint mikedoge ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "proof-of-airdrop",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2586837],
    title: "",
    logoUrl: null,
    subtitle: "Mint Proof of Airdrop",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "univ3rs",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2586977],
    title: "",
    logoUrl: null,
    subtitle: "Mint Univ3rs",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "suke",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2590016],
    title: "",
    logoUrl: null,
    subtitle: "Mint suke",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "petrolistul",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2592539],
    title: "",
    logoUrl: null,
    subtitle: "Mint Petrolistul",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "garagepunk",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2593216],
    title: "",
    logoUrl: null,
    subtitle: "Mint garagepunk",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tima",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2594809],
    title: "",
    logoUrl: null,
    subtitle: "Mint Tima",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "gotchi-french-army-x-sismo-live",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2595859],
    title: "",
    logoUrl: null,
    subtitle: "Mint Gotchi French Army x Sismo live",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "wagame-lens-post-interaction",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2597607],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wagame Lens fam ZK Badge",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cryptotelugu-lens",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2607278],
    title: "",
    logoUrl: null,
    subtitle: "Mint CryptoTelugu Lens",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "noxu",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2611247],
    title: "",
    logoUrl: null,
    subtitle: "Mint NOXU",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ionutcnmv",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2623862],
    title: "",
    logoUrl: null,
    subtitle: "Mint ionutcnmv",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "bullers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2628526],
    title: "",
    logoUrl: null,
    subtitle: "Mint Bullers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "siope",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2629178],
    title: "",
    logoUrl: null,
    subtitle: "Mint siope",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "all-for-web3",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2637617],
    title: "",
    logoUrl: null,
    subtitle: "Mint ALL For Web3",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mintanklee",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2642072],
    title: "",
    logoUrl: null,
    subtitle: "Mint Mintank",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "moon-dao",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2644694],
    title: "",
    logoUrl: null,
    subtitle: "Mint Moon Dao",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "0xlegion-lens-follower",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2648563],
    title: "",
    logoUrl: null,
    subtitle: "Mint  0xlegion.lens follower",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "degenscore-beacon",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Polygon, Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2658573],
    title: "",
    logoUrl: null,
    subtitle: "Mint DegenScore Beacon",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "steven",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2659684],
    title: "",
    logoUrl: null,
    subtitle: "Mint steven",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "xioshdezz",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2663668],
    title: "",
    logoUrl: null,
    subtitle: "Mint xioshdezz",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sismo-workshop-ethbrno",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2665855],
    title: "",
    logoUrl: null,
    subtitle: "Mint ETHBrno Sismo Workshop",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "early-wojak",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2673220],
    title: "",
    logoUrl: null,
    subtitle: "Mint Early WOJAK",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "oxbage",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2675416],
    title: "",
    logoUrl: null,
    subtitle: "Mint Oxman",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "op-airdrop",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2676733],
    title: "",
    logoUrl: null,
    subtitle: "Mint Top $OP Airdrop recipient (eligible for 5+ multipliers)",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "bonie-heads-yacht-club",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2691833],
    title: "",
    logoUrl: null,
    subtitle: "Mint Bonie Heads Yacht Club",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dmt",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2701706],
    title: "",
    logoUrl: null,
    subtitle: "Mint DMT",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rotterdamn-lens-follower",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2704885],
    title: "",
    logoUrl: null,
    subtitle: "Mint Rotterdamn Lens follower",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "xsant",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2706327],
    title: "",
    logoUrl: null,
    subtitle: "Mint XSanT",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "twitter",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2707024],
    title: "",
    logoUrl: null,
    subtitle: "Mint twitter",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "codedoge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2715945],
    title: "",
    logoUrl: null,
    subtitle: "Mint CodeDoge",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "anav-s-demo",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2715978],
    title: "",
    logoUrl: null,
    subtitle: "Mint Anav's Demo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "skynetwork",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2725949],
    title: "",
    logoUrl: null,
    subtitle: "Mint Skynetwork",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "etherium-eth-bit",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2729126],
    title: "",
    logoUrl: null,
    subtitle: "Mint etherium👍eth.bit",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "matsuta",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2734445],
    title: "",
    logoUrl: null,
    subtitle: "Mint matsuta",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "bgans",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2737080],
    title: "",
    logoUrl: null,
    subtitle: "Mint Bgans",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "offroadmann",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2741788],
    title: "",
    logoUrl: null,
    subtitle: "Mint offroadman",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mach-frens",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2742382],
    title: "",
    logoUrl: null,
    subtitle: "Mint Mach Frens",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "optimism-governance-committee-member",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2746764],
    title: "",
    logoUrl: null,
    subtitle: "Mint Optimism Governance Committee",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "saveasart",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2747461],
    title: "",
    logoUrl: null,
    subtitle: "Mint saveasART",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "jiangxiansen",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2750211],
    title: "",
    logoUrl: null,
    subtitle: "Mint jiangxiansen",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sismo-chocolate",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2751564],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sismo chocolate",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "phantabear",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2766635],
    title: "",
    logoUrl: null,
    subtitle: "Mint phantabear",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dhadrien-friends",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2773575],
    title: "",
    logoUrl: null,
    subtitle: "Mint Dhadrien github friends",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "karepmulah",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2774366],
    title: "",
    logoUrl: null,
    subtitle: "Mint Akuraposo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "b1y3-og-voters",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2778255],
    title: "",
    logoUrl: null,
    subtitle: "Mint B1Y3 OG Voters",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "delovoy-dao-christmas",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2782016],
    title: "",
    logoUrl: null,
    subtitle: "Mint Delovoy DAO Christmas",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "crypto-lemon",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2782044],
    title: "",
    logoUrl: null,
    subtitle: "Mint Crypto Lemon",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zksync-github-stargazers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Polygon, Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2808245],
    title: "",
    logoUrl: null,
    subtitle: "Mint zkSync Github stargazers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "skyweaver-conquest-player-season-12",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2814454],
    title: "",
    logoUrl: null,
    subtitle: "Mint Skyweaver Conquest player Season 12",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "jiraya-og-badge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2823307],
    title: "",
    logoUrl: null,
    subtitle: "Mint JiRaYa-OG",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "blocknodes",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2834144],
    title: "",
    logoUrl: null,
    subtitle: "Mint BlockNodes",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tpair",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2839426],
    title: "",
    logoUrl: null,
    subtitle: "Mint Qcrypto",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "anav-s-trial",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2842907],
    title: "",
    logoUrl: null,
    subtitle: "Mint Anav's Trial",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sismo-oarctic",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2853237],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sismo OArctic",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ratra",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2849437],
    title: "",
    logoUrl: null,
    subtitle: "Mint Ratra",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "twitter-follower",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2855348],
    title: "",
    logoUrl: null,
    subtitle: "Mint Twitter follower",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "grail-member",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2855723],
    title: "",
    logoUrl: null,
    subtitle: "Mint Grail Member",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "raul",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2869370],
    title: "",
    logoUrl: null,
    subtitle: "Mint Raul",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "bits5",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2870395],
    title: "",
    logoUrl: null,
    subtitle: "Mint Bits5",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tundra-players-club",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2871592],
    title: "",
    logoUrl: null,
    subtitle: "Mint Tundra Players Club",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "birdmore3-lens-follows",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2872818],
    title: "",
    logoUrl: null,
    subtitle: "Mint birdmore3.lens follows",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "polyx-exchange",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2874455],
    title: "",
    logoUrl: null,
    subtitle: "Mint PolyX Exchange",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "hazae41-github-followers",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2882494],
    title: "",
    logoUrl: null,
    subtitle: "Mint Haz GitHub Followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "anywhere-golden-customer",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2883815],
    title: "",
    logoUrl: null,
    subtitle: "Mint anywhere golden customer",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mr-crypto",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2890195],
    title: "",
    logoUrl: null,
    subtitle: "Mint Mr Crypto",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "david-zk-badge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2893168],
    title: "",
    logoUrl: null,
    subtitle: "Mint David",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sawuk",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2893437],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sawuk",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "empiredao-2023-5-day-desk-pass",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2900453],
    title: "",
    logoUrl: null,
    subtitle: "Mint EmpireDAO 2023 5 Day Desk Pass ZK Badge",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "eren-s-badge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2909098],
    title: "",
    logoUrl: null,
    subtitle: "Mint Trainspotting",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "the-doge-pound-owners",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2909110],
    title: "",
    logoUrl: null,
    subtitle: "Mint The Doge Pound Collector",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "albist-lens-follower",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2922851],
    title: "",
    logoUrl: null,
    subtitle: "Mint albist lens follower",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "my-zk-sismo",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2926703],
    title: "",
    logoUrl: null,
    subtitle: "Mint my zk sismo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "friend-of-0xba3-299d",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2927627],
    title: "",
    logoUrl: null,
    subtitle: "Mint Friend of 0xbA3...299d",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "coinking-contributor",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2927890],
    title: "",
    logoUrl: null,
    subtitle: "Mint coinking contributor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mcgregor",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2930059],
    title: "",
    logoUrl: null,
    subtitle: "Mint McGregor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "unumdao",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2931545],
    title: "",
    logoUrl: null,
    subtitle: "Mint UnumDAO",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "megumi",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2945455],
    title: "",
    logoUrl: null,
    subtitle: "Mint megumi",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ethereum-adopter",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2954371],
    title: "",
    logoUrl: null,
    subtitle: "Mint Ethereum Adopter",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "y-s--frens",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2957812],
    title: "",
    logoUrl: null,
    subtitle: "Mint Y林s' frens",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "all4you4",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2955432],
    title: "",
    logoUrl: null,
    subtitle: "Mint all4you4",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cryptomarketblog",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Gnosis, Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2960941],
    title: "",
    logoUrl: null,
    subtitle: "Mint CryptoMarketBlog",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "liver",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2967948],
    title: "",
    logoUrl: null,
    subtitle: "Mint Liver",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ambire-frens",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2968736],
    title: "",
    logoUrl: null,
    subtitle: "Mint Ambire Early In",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "gugulan",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis, Network.Polygon],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2969091],
    title: "",
    logoUrl: null,
    subtitle: "Mint Gugulan",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ray-s",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2976484],
    title: "",
    logoUrl: null,
    subtitle: "Mint Ray's",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "firstenquebadge",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2990121],
    title: "",
    logoUrl: null,
    subtitle: "Mint Enque Devs",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "chaotic-good-dao",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai, Network.Gnosis],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2992206],
    title: "",
    logoUrl: null,
    subtitle: "Mint Chaotic Good DAO",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ravi-zk-badge-on-sismo",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2994861],
    title: "",
    logoUrl: null,
    subtitle: "Mint Ravi zk Badge on Sismo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "maltsismo",
    attester: hydraS1AccountboundAttester.name,
    networks: [Network.Goerli, Network.Mumbai],
    attesterType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2997493],
    title: "",
    logoUrl: null,
    subtitle: "Mint maltchain",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
];
