import {
  hydraS1SimpleAttester,
  hydraS1SimpleBadges,
} from "@attestations-collections/playground/polygon/hydra-s1-simple";
import { Network } from "topics/attester";
import { Flow } from "topics/flow";

export const playgroundFactoryFlows: Flow[] = [
  {
    path: "coin-center-donators",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2106633],
    title: "",
    logoUrl: null,
    subtitle: "Mint Coin Center Donator",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "first-rug-on-lens",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2140799],
    title: "",
    logoUrl: null,
    subtitle: "Mint First Rug on Lens Protocol",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "martian-wave",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2213141],
    title: "",
    logoUrl: null,
    subtitle: "Mint martianwave",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mybadge",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2268502],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wegoham4trey friends",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "aurora",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2274842],
    title: "",
    logoUrl: null,
    subtitle: "Mint shiba",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "therealafrorickgroup",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2299239],
    title: "",
    logoUrl: null,
    subtitle: "Mint TheRealAfroRick",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ofac-chads-zk-badge-08-08-2022",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2336517],
    title: "",
    logoUrl: null,
    subtitle: "Mint OFAC chads",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ens-contracts-stargazers",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2364118],
    title: "",
    logoUrl: null,
    subtitle: "Mint [playground]  Ens Contracts Stargazers ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rocketlab",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2537705],
    title: "",
    logoUrl: null,
    subtitle: "Mint rocketlab",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "blockimperiumgames",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2569984],
    title: "",
    logoUrl: null,
    subtitle: "Mint BlockImperiumGames",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "wagame-lens-post-interaction",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2597607],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wagame Lens fam ZK Badge",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "op-airdrop",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2676733],
    title: "",
    logoUrl: null,
    subtitle: "Mint Top $OP Airdrop recipient (eligible for 5+ multipliers)",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dmt",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2701706],
    title: "",
    logoUrl: null,
    subtitle: "Mint DMT",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dhadrien-friends",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2773575],
    title: "",
    logoUrl: null,
    subtitle: "Mint Dhadrien github friends",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "david-zk-badge",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2893168],
    title: "",
    logoUrl: null,
    subtitle: "Mint David",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "the-doge-pound-owners",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2909110],
    title: "",
    logoUrl: null,
    subtitle: "Mint The Doge Pound Collector",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "firstenquebadge",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [2990121],
    title: "",
    logoUrl: null,
    subtitle: "Mint Enque Devs",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  // {
  //   path: "proof-of-attendance",
  //   attester: hydraS1SimpleAttester.name,
  //   network: Network.Polygon,
  //   attesterType: "hydra-s1",
  //   badgesCollection: hydraS1SimpleBadges,
  //   badgesInternalCollectionsIds: [3000000],
  //   title: "POAP",
  //   logoUrl: null,
  //   subtitle: "Prove that you attended Ethereum events",
  //   ctaLabel: "See my badge",
  //   ctaUrl: "",
  //   congratulationTexts: [
  //     "You can now prove that you",
  //     "attended Ethereum events",
  //   ],
  // },
];
