import {
  hydraS1AccountboundRegistryTreeConfig,
  hydraS1AccountboundBadges,
} from "@badges-metadata/playground/hydra-s1-accountbound";
import { Network } from "topics/registry-tree";
import { Flow } from "topics/flow";

export const playgroundFactoryFlows: Flow[] = [
  {
    path: "helper",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2017027],
    title: "",
    logoUrl: null,
    subtitle: "Mint Helper",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "gen-0-dagorians",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2027048],
    title: "",
    logoUrl: null,
    subtitle: "Mint Gen[0] dAgorians",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sismo-meme",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2020053],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sismo meme",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zklend-poap-contributor",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2042020],
    title: "",
    logoUrl: null,
    subtitle: "Mint zkLend POAP contributor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rahulkr-lens-followers",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2055365],
    title: "",
    logoUrl: null,
    subtitle: "Mint RAHULKR LENS FOLLOWERS",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lens-meme-collector-mirror",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2064170],
    title: "",
    logoUrl: null,
    subtitle: "Mint LENS meme collector,mirror",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tokenomics-dao-consultant",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2092300],
    title: "",
    logoUrl: null,
    subtitle: "Mint Consultant",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "coin-center-donators",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2106633],
    title: "",
    logoUrl: null,
    subtitle: "Mint Coin Center Donator",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "viktor",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2137451],
    title: "",
    logoUrl: null,
    subtitle: "Mint Viktor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "first-rug-on-lens",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2140799],
    title: "",
    logoUrl: null,
    subtitle: "Mint First Rug on Lens Protocol",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "monsters",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2153882],
    title: "",
    logoUrl: null,
    subtitle: "Mint Monsterwear",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "commitdao",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2163624],
    title: "",
    logoUrl: null,
    subtitle: "Mint CommitDAO",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lama-pama",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2174030],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lama Pama",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cryptomonkeys",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2184873],
    title: "",
    logoUrl: null,
    subtitle: "Mint CryptoMonkeys ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "madmax-badge",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2184978],
    title: "",
    logoUrl: null,
    subtitle: "Mint madmax",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "martian-wave",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2213141],
    title: "",
    logoUrl: null,
    subtitle: "Mint martianwave",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "relay-badge",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2216993],
    title: "",
    logoUrl: null,
    subtitle: "Mint Relay Team",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "with-love-from-bykur",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2234775],
    title: "",
    logoUrl: null,
    subtitle: "Mint With love from bykur",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "oldschool",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2240101],
    title: "",
    logoUrl: null,
    subtitle: "Mint Oldschool",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "neoneo-badge",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2248171],
    title: "",
    logoUrl: null,
    subtitle: "Mint NeoNeo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zk-hack",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2267301],
    title: "",
    logoUrl: null,
    subtitle: "Mint ZK Hack",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mybadge",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2268502],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wegoham4trey friends",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "aurora",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2274842],
    title: "",
    logoUrl: null,
    subtitle: "Mint shiba",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dorg-members",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2280940],
    title: "",
    logoUrl: null,
    subtitle: "Mint dOrg",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "therealafrorickgroup",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2299239],
    title: "",
    logoUrl: null,
    subtitle: "Mint TheRealAfroRick",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "proof-of-loneliness",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2315671],
    title: "",
    logoUrl: null,
    subtitle: "Mint Proof of Loneliness",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dual-pepes",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2329542],
    title: "",
    logoUrl: null,
    subtitle: "Mint Dual Pepes",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ofac-chads-zk-badge-08-08-2022",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2336517],
    title: "",
    logoUrl: null,
    subtitle: "Mint OFAC chads",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "nftyard-lens-follower",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2340668],
    title: "",
    logoUrl: null,
    subtitle: "Mint Nftyard lens follower",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lens-followers",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2345464],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lens Followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "thub-contributor",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2348016],
    title: "",
    logoUrl: null,
    subtitle: "Mint THUB Contributor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ens-contracts-stargazers",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2364118],
    title: "",
    logoUrl: null,
    subtitle: "Mint [playground]  Ens Contracts Stargazers ",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "padultra",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2398819],
    title: "",
    logoUrl: null,
    subtitle: "Mint padultra",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "lands",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2399049],
    title: "",
    logoUrl: null,
    subtitle: "Mint Lands",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "offscript-attendee",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2405819],
    title: "",
    logoUrl: null,
    subtitle: "Mint Offscript attendee",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "kung-fu",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2422521],
    title: "",
    logoUrl: null,
    subtitle: "Mint Kung Fu",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "empiredao-2023-1-day-desk-pass",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2471201],
    title: "",
    logoUrl: null,
    subtitle: "Mint EmpireDAO 2023 1 Day Desk Pass",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "swapper-armyfox",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2481714],
    title: "",
    logoUrl: null,
    subtitle: "Mint Swapper Armyfox",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rekt-familly-degen",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2484699],
    title: "",
    logoUrl: null,
    subtitle: "Mint REKT Familly degen",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zk-hack-iii-sismo-workshop",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2489013],
    title: "",
    logoUrl: null,
    subtitle: "Mint ZK HACK III - Sismo Workshop",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "wonder",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2493562],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wonder",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "my-09",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2504053],
    title: "",
    logoUrl: null,
    subtitle: "Mint ape",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tally-ho-github-stargazers",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2513336],
    title: "",
    logoUrl: null,
    subtitle: "Mint Tally Ho Github stargazers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "rocketlab",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2537705],
    title: "",
    logoUrl: null,
    subtitle: "Mint rocketlab",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "fiona",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2545308],
    title: "",
    logoUrl: null,
    subtitle: "Mint fiona",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "wallet-group",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2558435],
    title: "",
    logoUrl: null,
    subtitle: "Mint money dog🐶(OG)",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sk",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2569336],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sk",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "blockimperiumgames",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2569984],
    title: "",
    logoUrl: null,
    subtitle: "Mint BlockImperiumGames",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tokenomics-dao-contributor",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2573021],
    title: "",
    logoUrl: null,
    subtitle: "Mint Tokenomics DAO Contributor",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "akamo",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2577616],
    title: "",
    logoUrl: null,
    subtitle: "Mint akamo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "igorsgemsdao",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2579312],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sismo IgorsGemsDao",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tima",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2594809],
    title: "",
    logoUrl: null,
    subtitle: "Mint Tima",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "gotchi-french-army-x-sismo-live",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2595859],
    title: "",
    logoUrl: null,
    subtitle: "Mint Gotchi French Army x Sismo live",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "wagame-lens-post-interaction",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2597607],
    title: "",
    logoUrl: null,
    subtitle: "Mint Wagame Lens fam ZK Badge",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cryptotelugu-lens",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2607278],
    title: "",
    logoUrl: null,
    subtitle: "Mint CryptoTelugu Lens",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "mintanklee",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2642072],
    title: "",
    logoUrl: null,
    subtitle: "Mint Mintank",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "moon-dao",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2644694],
    title: "",
    logoUrl: null,
    subtitle: "Mint Moon Dao",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "degenscore-beacon",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2658573],
    title: "",
    logoUrl: null,
    subtitle: "Mint DegenScore Beacon",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sismo-workshop-ethbrno",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2665855],
    title: "",
    logoUrl: null,
    subtitle: "Mint ETHBrno Sismo Workshop",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "oxbage",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2675416],
    title: "",
    logoUrl: null,
    subtitle: "Mint Oxman",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "op-airdrop",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2676733],
    title: "",
    logoUrl: null,
    subtitle: "Mint Top $OP Airdrop recipient (eligible for 5+ multipliers)",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dmt",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2701706],
    title: "",
    logoUrl: null,
    subtitle: "Mint DMT",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "xsant",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2706327],
    title: "",
    logoUrl: null,
    subtitle: "Mint XSanT",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "anav-s-demo",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2715978],
    title: "",
    logoUrl: null,
    subtitle: "Mint Anav's Demo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "etherium-eth-bit",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2729126],
    title: "",
    logoUrl: null,
    subtitle: "Mint etherium👍eth.bit",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "offroadmann",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2741788],
    title: "",
    logoUrl: null,
    subtitle: "Mint offroadman",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "optimism-governance-committee-member",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2746764],
    title: "",
    logoUrl: null,
    subtitle: "Mint Optimism Governance Committee",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "phantabear",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2766635],
    title: "",
    logoUrl: null,
    subtitle: "Mint phantabear",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "dhadrien-friends",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2773575],
    title: "",
    logoUrl: null,
    subtitle: "Mint Dhadrien github friends",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "karepmulah",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2774366],
    title: "",
    logoUrl: null,
    subtitle: "Mint Akuraposo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "b1y3-og-voters",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2778255],
    title: "",
    logoUrl: null,
    subtitle: "Mint B1Y3 OG Voters",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "delovoy-dao-christmas",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2782016],
    title: "",
    logoUrl: null,
    subtitle: "Mint Delovoy DAO Christmas",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "zksync-github-stargazers",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2808245],
    title: "",
    logoUrl: null,
    subtitle: "Mint zkSync Github stargazers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "skyweaver-conquest-player-season-12",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2814454],
    title: "",
    logoUrl: null,
    subtitle: "Mint Skyweaver Conquest player Season 12",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "jiraya-og-badge",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2823307],
    title: "",
    logoUrl: null,
    subtitle: "Mint JiRaYa-OG",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tpair",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2839426],
    title: "",
    logoUrl: null,
    subtitle: "Mint Qcrypto",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "anav-s-trial",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2842907],
    title: "",
    logoUrl: null,
    subtitle: "Mint Anav's Trial",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "grail-member",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2855723],
    title: "",
    logoUrl: null,
    subtitle: "Mint Grail Member",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "tundra-players-club",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2871592],
    title: "",
    logoUrl: null,
    subtitle: "Mint Tundra Players Club",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "polyx-exchange",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2874455],
    title: "",
    logoUrl: null,
    subtitle: "Mint PolyX Exchange",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "hazae41-github-followers",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2882494],
    title: "",
    logoUrl: null,
    subtitle: "Mint Haz GitHub Followers",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "anywhere-golden-customer",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2883815],
    title: "",
    logoUrl: null,
    subtitle: "Mint anywhere golden customer",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "david-zk-badge",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2893168],
    title: "",
    logoUrl: null,
    subtitle: "Mint David",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "sawuk",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2893437],
    title: "",
    logoUrl: null,
    subtitle: "Mint Sawuk",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "empiredao-2023-5-day-desk-pass",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2900453],
    title: "",
    logoUrl: null,
    subtitle: "Mint EmpireDAO 2023 5 Day Desk Pass ZK Badge",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "eren-s-badge",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2909098],
    title: "",
    logoUrl: null,
    subtitle: "Mint Trainspotting",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "the-doge-pound-owners",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2909110],
    title: "",
    logoUrl: null,
    subtitle: "Mint The Doge Pound Collector",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "friend-of-0xba3-299d",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2927627],
    title: "",
    logoUrl: null,
    subtitle: "Mint Friend of 0xbA3...299d",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "unumdao",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2931545],
    title: "",
    logoUrl: null,
    subtitle: "Mint UnumDAO",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "cryptomarketblog",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2960941],
    title: "",
    logoUrl: null,
    subtitle: "Mint CryptoMarketBlog",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "liver",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2967948],
    title: "",
    logoUrl: null,
    subtitle: "Mint Liver",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ambire-frens",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2968736],
    title: "",
    logoUrl: null,
    subtitle: "Mint Ambire Early In",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "firstenquebadge",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2990121],
    title: "",
    logoUrl: null,
    subtitle: "Mint Enque Devs",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "ravi-zk-badge-on-sismo",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2994861],
    title: "",
    logoUrl: null,
    subtitle: "Mint Ravi zk Badge on Sismo",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
  {
    path: "maltsismo",
    registryTree: hydraS1AccountboundRegistryTreeConfig.name,
    networks: [Network.Polygon],
    registryTreeType: "hydra-s1",
    badgesCollection: hydraS1AccountboundBadges,
    badgesInternalCollectionsIds: [2997493],
    title: "",
    logoUrl: null,
    subtitle: "Mint maltchain",
    ctaLabel: "",
    ctaUrl: "",
    congratulationTexts: [],
  },
];
