import {
  hydraS1AccountboundAttester,
  hydraS1AccountboundBadges,
} from "@badges-metadata/playground/hydra-s1-accountbound";
import { Network } from "topics/attester";
import { Flow } from "topics/flow";

export const stagingFactoryFlows: Flow[] = [];

for (const network of [Network.Mumbai, Network.Goerli]) {
  const flows = [
    {
      path: "tokenomics-dao-consultant",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2092300],
      title: "",
      logoUrl: null,
      subtitle: "Mint Consultant",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "coin-center-donators",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2106633],
      title: "",
      logoUrl: null,
      subtitle: "Mint Coin Center Donator",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "first-rug-on-lens",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2140799],
      title: "",
      logoUrl: null,
      subtitle: "Mint First Rug on Lens Protocol",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "monsters",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2153882],
      title: "",
      logoUrl: null,
      subtitle: "Mint Monsterwear",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "commitdao",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2163624],
      title: "",
      logoUrl: null,
      subtitle: "Mint CommitDAO",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "lama-pama",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2174030],
      title: "",
      logoUrl: null,
      subtitle: "Mint Lama Pama",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "madmax-badge",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2184978],
      title: "",
      logoUrl: null,
      subtitle: "Mint madmax",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "martian-wave",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2213141],
      title: "",
      logoUrl: null,
      subtitle: "Mint martianwave",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "relay-badge",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2216993],
      title: "",
      logoUrl: null,
      subtitle: "Mint Relay Team",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "neoneo-badge",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2248171],
      title: "",
      logoUrl: null,
      subtitle: "Mint NeoNeo",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "zk-hack",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2267301],
      title: "",
      logoUrl: null,
      subtitle: "Mint ZK Hack",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "mybadge",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2268502],
      title: "",
      logoUrl: null,
      subtitle: "Mint Wegoham4trey friends",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "aurora",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2274842],
      title: "",
      logoUrl: null,
      subtitle: "Mint shiba",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "dorg-members",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2280940],
      title: "",
      logoUrl: null,
      subtitle: "Mint dOrg",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "therealafrorickgroup",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2299239],
      title: "",
      logoUrl: null,
      subtitle: "Mint TheRealAfroRick",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "dual-pepes",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2329542],
      title: "",
      logoUrl: null,
      subtitle: "Mint Dual Pepes",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "ofac-chads-zk-badge-08-08-2022",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2336517],
      title: "",
      logoUrl: null,
      subtitle: "Mint OFAC chads",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "thub-contributor",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2348016],
      title: "",
      logoUrl: null,
      subtitle: "Mint THUB Contributor",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "ens-contracts-stargazers",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2364118],
      title: "",
      logoUrl: null,
      subtitle: "Mint [playground]  Ens Contracts Stargazers ",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "padultra",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2398819],
      title: "",
      logoUrl: null,
      subtitle: "Mint padultra",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "offscript-attendee",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2405819],
      title: "",
      logoUrl: null,
      subtitle: "Mint Offscript attendee",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "kung-fu",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2422521],
      title: "",
      logoUrl: null,
      subtitle: "Mint Kung Fu",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "zk-hack-iii-sismo-workshop",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2489013],
      title: "",
      logoUrl: null,
      subtitle: "Mint ZK HACK III - Sismo Workshop",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "my-09",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2504053],
      title: "",
      logoUrl: null,
      subtitle: "Mint ape",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "rocketlab",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2537705],
      title: "",
      logoUrl: null,
      subtitle: "Mint rocketlab",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "fiona",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2545308],
      title: "",
      logoUrl: null,
      subtitle: "Mint fiona",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "wallet-group",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2558435],
      title: "",
      logoUrl: null,
      subtitle: "Mint money dog🐶(OG)",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "blockimperiumgames",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2569984],
      title: "",
      logoUrl: null,
      subtitle: "Mint BlockImperiumGames",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "tokenomics-dao-contributor",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2573021],
      title: "",
      logoUrl: null,
      subtitle: "Mint Tokenomics DAO Contributor",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "akamo",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2577616],
      title: "",
      logoUrl: null,
      subtitle: "Mint akamo",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "igorsgemsdao",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2579312],
      title: "",
      logoUrl: null,
      subtitle: "Mint Sismo IgorsGemsDao",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "gotchi-french-army-x-sismo-live",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2595859],
      title: "",
      logoUrl: null,
      subtitle: "Mint Gotchi French Army x Sismo live",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "wagame-lens-post-interaction",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2597607],
      title: "",
      logoUrl: null,
      subtitle: "Mint Wagame Lens fam ZK Badge",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "mintanklee",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2642072],
      title: "",
      logoUrl: null,
      subtitle: "Mint Mintank",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "sismo-workshop-ethbrno",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2665855],
      title: "",
      logoUrl: null,
      subtitle: "Mint ETHBrno Sismo Workshop",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "oxbage",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2675416],
      title: "",
      logoUrl: null,
      subtitle: "Mint Oxman",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "op-airdrop",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2676733],
      title: "",
      logoUrl: null,
      subtitle: "Mint Top $OP Airdrop recipient (eligible for 5+ multipliers)",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "dmt",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2701706],
      title: "",
      logoUrl: null,
      subtitle: "Mint DMT",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "anav-s-demo",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2715978],
      title: "",
      logoUrl: null,
      subtitle: "Mint Anav's Demo",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "etherium-eth-bit",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2729126],
      title: "",
      logoUrl: null,
      subtitle: "Mint etherium👍eth.bit",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "offroadmann",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2741788],
      title: "",
      logoUrl: null,
      subtitle: "Mint offroadman",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "optimism-governance-committee-member",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2746764],
      title: "",
      logoUrl: null,
      subtitle: "Mint Optimism Governance Committee",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "dhadrien-friends",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2773575],
      title: "",
      logoUrl: null,
      subtitle: "Mint Dhadrien github friends",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "karepmulah",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2774366],
      title: "",
      logoUrl: null,
      subtitle: "Mint Akuraposo",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "skyweaver-conquest-player-season-12",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2814454],
      title: "",
      logoUrl: null,
      subtitle: "Mint Skyweaver Conquest player Season 12",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "jiraya-og-badge",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2823307],
      title: "",
      logoUrl: null,
      subtitle: "Mint JiRaYa-OG",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "tpair",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2839426],
      title: "",
      logoUrl: null,
      subtitle: "Mint Qcrypto",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "anav-s-trial",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2842907],
      title: "",
      logoUrl: null,
      subtitle: "Mint Anav's Trial",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "grail-member",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2855723],
      title: "",
      logoUrl: null,
      subtitle: "Mint Grail Member",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "tundra-players-club",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2871592],
      title: "",
      logoUrl: null,
      subtitle: "Mint Tundra Players Club",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "polyx-exchange",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2874455],
      title: "",
      logoUrl: null,
      subtitle: "Mint PolyX Exchange",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "hazae41-github-followers",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2882494],
      title: "",
      logoUrl: null,
      subtitle: "Mint Haz GitHub Followers",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "anywhere-golden-customer",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2883815],
      title: "",
      logoUrl: null,
      subtitle: "Mint anywhere golden customer",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "david-zk-badge",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2893168],
      title: "",
      logoUrl: null,
      subtitle: "Mint David",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "sawuk",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2893437],
      title: "",
      logoUrl: null,
      subtitle: "Mint Sawuk",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "eren-s-badge",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2909098],
      title: "",
      logoUrl: null,
      subtitle: "Mint Trainspotting",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "the-doge-pound-owners",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2909110],
      title: "",
      logoUrl: null,
      subtitle: "Mint The Doge Pound Collector",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "friend-of-0xba3-299d",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2927627],
      title: "",
      logoUrl: null,
      subtitle: "Mint Friend of 0xbA3...299d",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "liver",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2967948],
      title: "",
      logoUrl: null,
      subtitle: "Mint Liver",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "ambire-frens",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2968736],
      title: "",
      logoUrl: null,
      subtitle: "Mint Ambire Early In",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "firstenquebadge",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2990121],
      title: "",
      logoUrl: null,
      subtitle: "Mint Enque Devs",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "ravi-zk-badge-on-sismo",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2994861],
      title: "",
      logoUrl: null,
      subtitle: "Mint Ravi zk Badge on Sismo",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    {
      path: "maltsismo",
      attester: hydraS1AccountboundAttester.name,
      network,
      attesterType: "hydra-s1",
      badgesCollection: hydraS1AccountboundBadges,
      badgesInternalCollectionsIds: [2997493],
      title: "",
      logoUrl: null,
      subtitle: "Mint maltchain",
      ctaLabel: "",
      ctaUrl: "",
      congratulationTexts: [],
    },
    // {
    //   path: "proof-of-attendance",
    //   attester: hydraS1AccountboundAttester.name,
    //   network,
    //   attesterType: "hydra-s1",
    //   badgesCollection: hydraS1AccountboundBadges,
    //   badgesInternalCollectionsIds: [3000000],
    //   title: "POAP",
    //   logoUrl: null,
    //   subtitle: "Prove that you attended Ethereum events",
    //   ctaLabel: "See my badge",
    //   ctaUrl: "",
    //   congratulationTexts: [
    //     "You can now prove that you",
    //     "attended Ethereum events",
    //   ],
    // },
  ];

  stagingFactoryFlows.push(...flows)
}
