import {
  hydraS1SimpleAttester,
  hydraS1SimpleBadges,
} from "@attestations-collections/playground/polygon/hydra-s1-simple";
import { pythia1SimpleBadges } from "@attestations-collections/playground/polygon/pythia-1-simple";
import { Network } from "topics/attester";
import { Flow } from "topics/flow";

const gamejutsuCommon = { 
  attester: hydraS1SimpleAttester.name,
  network: Network.Polygon,
  attesterType: "hydra-s1",
  badgesCollection: hydraS1SimpleBadges,
  logoUrl: null,
  onboardingDescription: "Access gated GameJutsu channel and become an active member of the ChainHackers state channel gamers", // hype your users !
  ctaLabel: "Access gated channels",
  ctaUrl: "https://discord.gg/a5E9vWbp9R",
  congratulationTexts: ["Welcome to the miracle!"],
}

export const playgroundFlows: Flow[] = [
  {
    path: "ethereum-power-users",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [4],
    title: "",
    logoUrl: null,
    subtitle: "Join Ethereum Power Users community",
    onboardingDescription:
      "Prove you are one of the biggest Ethereum users and access the governance around the badge on snapshot.",
    ctaLabel: "Access gated channel",
    ctaUrl: "https://discord.gg/sismo",
    congratulationTexts: ["Provide feedback on Discord", "Join Snapshot Space"],
  },
  {
    path: "safe-alert",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [5, 6, 7],
    title: "Safe Alert",
    logoUrl: null,
    subtitle: "Join Safe Alert community",
    onboardingDescription:
      "Safe alert is a dApp that protect the white hats interests by provinding them with a secure way to alert protocols of detected bugs and provinding them with a way to aassess publicly their skils and contribution.",
    ctaLabel: "Go Back to Safe Alert",
    ctaUrl: "http://localhost:3000/",
    congratulationTexts: ["Congratulations !"],
  },
  {
    path: "proof-of-humanity",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [8],
    title: "Proof of Humanity",
    logoUrl: null,
    subtitle: "Prove you are a human with privacy",
    onboardingDescription:
      "This ZK Badge is an attestation proving that you are a human. It is used by diverse applications (e.g Lens) as a sybil resistant tool",
    ctaLabel: "See your badge",
    ctaUrl: "",
    congratulationTexts: [
      "You can now prove that you are a human",
      "and access human-gated services!",
    ],
  },
  {
    path: "synaps-liveness",
    attester: "pythia-1-simple",
    network: Network.Polygon,
    attesterType: "pythia-1",
    badgesCollection: pythia1SimpleBadges,
    badgesInternalCollectionsIds: [0],
    title: "Synaps",
    logoUrl: null,
    subtitle: "Prove you are not a bot",
    onboardingDescription:
      "This ZK Badge is an attestation that you are a human and not a bot. It is used by diverse applications (e.g Lens) as a sybil resistant tool.",
    ctaLabel: "See your badge",
    ctaUrl: "",
    congratulationTexts: [
      "You can now prove that you are",
      "not a bot by showing this badge!",
    ],
  },
  {
    path: "proof-of-lepak-member",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1-simple",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [9],
    title: "Proof of Lepak Member",
    logoUrl: null,
    subtitle: "Prove you are a member from Lepak DAO",
    onboardingDescription:
      "This ZK Badge is an attestation proving that you are a Lepak Member. After getting your zkBadge, you are eligible for voting in Lepak DAO",
    ctaLabel: "See your badge",
    ctaUrl: "",
    congratulationTexts: ["You can now prove that you are a Lepak Member"],
  },
  {
    path: "circularmerch-lens-followers",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [10],
    title: "CircularMerch",
    logoUrl: null,
    subtitle: "Get your ticket",
    onboardingDescription: "Prove you follow Circlemerch",
    ctaLabel: "See your badges",
    ctaUrl: "",
    congratulationTexts: ["1. Congratulation"],
  },
  {
    path: "lens-50-best-followed",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [11],
    title: "50 most Followed",
    logoUrl: null,
    subtitle: "Get your ticket",
    onboardingDescription: "Prove you are 50 most followed",
    ctaLabel: "See your badges",
    ctaUrl: "",
    congratulationTexts: ["1. Congratulation"],
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [12],
    path: "gamejutsu-bronze-winner",
    title: "White Winner",
    subtitle: "Attest your first win at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [13],
    path: "gamejutsu-silver-winner",
    title: "Green Winner",
    subtitle: "Attest your fifth repetitive win at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [14],
    path: "gamejutsu-gold-winner",
    title: "Black Winner",
    subtitle: "Attest your 10th repetitive win at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [15],
    path: "gamejutsu-bronze-loser",
    title: "White Loser",
    subtitle: "Attest your first lose at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [16],
    path: "gamejutsu-silver-loser", 
    title: "Green Loser",
    subtitle: "Attest your fifth repetitive lose at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [17],
    path: "gamejutsu-gold-loser",
    title: "Black Loser",
    subtitle: "Attest your 10th repetitive lose at gamejutsu.app at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [18],
    path: "gamejutsu-bronze-draw",
    title: "White Peacemonger",
    subtitle: "Attest your first draw at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [19],
    path: "gamejutsu-silver-draw",
    title: "Green Peacemonger",
    subtitle: "Attest your fifth repetitive draw at gamejutsu.app at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [20],
    path: "gamejutsu-gold-draw",
    title: "Black Peacemonger",
    subtitle: "Attest your 10th repetitive draw at gamejutsu.app at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [21],
    path: "gamejutsu-bronze-cheater",
    title: "White Belt In Cheating",
    subtitle: "Attest your first cheat at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [22],
    path: "gamejutsu-silver-cheater",
    title: "Green Belt In Cheating",
    subtitle: "Attest your fifth repetitive cheat at gamejutsu.app at gamejutsu.app",
  },
  {
    ...gamejutsuCommon,
    badgesInternalCollectionsIds: [23],
    path: "gamejutsu-gold-cheater",
    title: "Black Belt In Cheating",
    subtitle: "Attest your 10th repetitive cheat at gamejutsu.app at gamejutsu.app",
  },
  {
    path: "sismo-contributor",
    attester: hydraS1SimpleAttester.name,
    network: Network.Polygon,
    attesterType: "hydra-s1",
    badgesCollection: hydraS1SimpleBadges,
    badgesInternalCollectionsIds: [5151110],
    title: "",
    logoUrl: null,
    subtitle: "Join Sismo Contributors Community",
    onboardingDescription:
      "This ZK Badge is an attestation that you are part of Sismo. You will be able to use it in Sismo Governance to voice your opinion and become owner of the project.",
    ctaLabel: "Join our discord",
    ctaUrl: "https://discord.gg/sismo",
    congratulationTexts: [
      "Thank you so much! We hope to see",
      "you further involved in Sismo",
    ],
  },
];
