name: Deploy playground environment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Playground
    runs-on: ubuntu-latest
    environment:
      name: playground
      url: https://hub.playground.sismo.io/doc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update groups and send on-chain
        uses: ./.github/actions/update-groups-send-on-chain
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_EXECUTION_ROLE }} 
          sh-s3-data-bucket-name: "sismo-playground-hub-data"
          sh-s3-data-endpoint: "https://sismo-playground-hub-data.s3.eu-west-1.amazonaws.com"
          sh-dynamodb-global-table-name: sismo-playground-hub-global-table
          sh-default-configuration-env: playground
          sh-relay-defender-api-keys: ${{ secrets.SH_RELAY_DEFENDER_API_KEYS }}
          sh-first-generation-only: "yes"
          decentralized-subgraph-api-key: ${{ secrets.DECENTRALIZED_SUBGRAPH_API_KEY }} 
          google-application-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  
          sh-attesters: hydra-s1-simple hydra-s1-accountbound  
          sh-attesters-networks: polygon
          hive-api-key: ${{ secrets.HIVE_API_KEY }}
          twitter-api-key: ${{ secrets.TWITTER_API_KEY }}
          json-rpc-url: ${{ secrets.JSON_RPC_URL }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          github-token: ${{ secrets.SH_GITHUB_TOKEN }}
          transpose-api-key: ${{ secrets.TRANSPOSE_API_KEY }}
      - name: Build and deploy
        uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          stage: playground
          static-bucket-name: ${{ secrets.STATIC_BUCKET_NAME }}
          deployment-url: "https://hub.playground.sismo.io/"
          hive-api-key: ${{ secrets.HIVE_API_KEY }}
          github-token: ${{ secrets.SH_GITHUB_TOKEN }}
