name: Deploy staging environment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Playground
    runs-on: ubuntu-latest
    environment:
      name: playground
      url: https://hub.playground.sismo.io/doc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy
        uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          stage: playground
          static-bucket-name: ${{ secrets.STATIC_BUCKET_NAME }}
          deployment-url: "https://hub.playground.sismo.io/"
