name: Generate group Testnets
on:
  workflow_dispatch:
    inputs:
      group-generator-name:
        description: "Group generator name"
        required: true

jobs:
  generate-group-testnets:
    name: Generate Group Testnets
    runs-on: ubuntu-latest
    environment:
      name: testnets
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: generate group and send on-chain
        uses: ./.github/actions/generate-group-send-on-chain
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_EXECUTION_ROLE }}
          sh-s3-data-bucket-name: "sismo-testnets-hub-data"
          sh-s3-data-endpoint: "https://sismo-testnets-hub-data.s3.eu-west-1.amazonaws.com"
          sh-dynamodb-global-table-name: sismo-testnets-hub-global-table
          sh-default-configuration-env: testnets
          sh-relay-defender-api-keys: ${{ secrets.SH_RELAY_DEFENDER_API_KEYS }}
          roots-registry-owner-mnemonic: ${{ secrets.ROOTS_REGISTRY_OWNER_MNEMONIC }}
          sh-last-generation-time-interval: "0"
          sh-group-generator-name: ${{ inputs.group-generator-name }}
          sh-attesters: hydra-s1-accountbound
          sh-attesters-networks: goerli mumbai
          hive-api-key: ${{ secrets.HIVE_API_KEY }}
          alchemy-api-key: ${{ secrets.ALCHEMY_API_KEY }}
          twitter-api-key: ${{ secrets.TWITTER_API_KEY }}
          json-rpc-url: ${{ secrets.JSON_RPC_URL }}
          sh-ignore-resolving-errors: "false"
          decentralized-subgraph-api-key: ${{ secrets.DECENTRALIZED_SUBGRAPH_API_KEY }}
          google-application-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          github-token: ${{ secrets.SH_GITHUB_TOKEN }}
          transpose-api-key: ${{ secrets.TRANSPOSE_API_KEY }}
          farcaster-api-key: ${{ secrets.FARCASTER_API_KEY }}
          dune-api-key: ${{secrets.DUNE_API_KEY}}
          gitcoin-api-key: ${{ secrets.GITCOIN_API_KEY }}
          ankr-api-key: ${{ secrets.ANKR_API_KEY }}
