name: Update group metadata Testnets
on:
  workflow_dispatch:
    inputs:
      group-generator-name:
        description: "Group generator name"
        required: true

jobs:
  update-group-metadata-testnets:
    name: Update group metadata Testnets
    runs-on: ubuntu-latest
    environment:
      name: testnets
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: update group metadata
        uses: ./.github/actions/update-group-metadata
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_EXECUTION_ROLE }}
          sh-s3-data-bucket-name: "sismo-testnets-hub-data"
          sh-s3-data-endpoint: "https://sismo-testnets-hub-data.s3.eu-west-1.amazonaws.com"
          sh-dynamodb-global-table-name: sismo-testnets-hub-global-table
          sh-default-configuration-env: testnets
          sh-group-generator-name: ${{ inputs.group-generator-name }}
          hive-api-key: ${{ secrets.HIVE_API_KEY }}
          alchemy-api-key: ${{ secrets.ALCHEMY_API_KEY }}
          json-rpc-url: ${{ secrets.JSON_RPC_URL }}
          decentralized-subgraph-api-key: ${{ secrets.DECENTRALIZED_SUBGRAPH_API_KEY }}
          google-application-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          transpose-api-key: ${{ secrets.TRANSPOSE_API_KEY }}
          dune-api-key: ${{secrets.DUNE_API_KEY}}
          gitcoin-api-key: ${{ secrets.GITCOIN_API_KEY }}
          ankr-api-key: ${{ secrets.ANKR_API_KEY }}
          github-token: ${{ secrets.SH_GITHUB_TOKEN }}
          twitter-api-key: ${{ secrets.TWITTER_API_KEY }}
          telegram-api-hash: ${{ secrets.TELEGRAM_API_HASH }}
          telegram-api-id: ${{ secrets.TELEGRAM_API_ID }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-bot-session: ${{ secrets.TELEGRAM_BOT_SESSION }}
          roci-api-key: ${{ secrets.ROCI_API_KEY }}
