name: ⚠️ Delete groups Testnets
on:
  workflow_dispatch:
    inputs:
      group-names:
        description: "Group names"
        required: true

jobs:
  delete-groups-testnets:
    name: Delete groups Testnets
    runs-on: ubuntu-latest
    environment:
      name: testnets
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: delete groups
        uses: ./.github/actions/delete-groups
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_EXECUTION_ROLE }}
          sh-s3-data-bucket-name: "sismo-testnets-hub-data"
          sh-s3-data-endpoint: "https://sismo-testnets-hub-data.s3.eu-west-1.amazonaws.com"
          sh-dynamodb-global-table-name: sismo-testnets-hub-global-table
          sh-default-configuration-env: testnets
          sh-group-names: ${{ inputs.group-names }}
          sh-relay-defender-api-keys: ${{ secrets.SH_RELAY_DEFENDER_API_KEYS }}
          sh-additional-data: ${{ env.ADDITIONAL_DATA }}
          sh-attesters-networks: goerli mumbai
          sh-registry-tree-networks: goerli
          sh-attesters: hydra-s1-accountbound
